name: Test

on:
  pull_request:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual run'
        required: false

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      # Free disk space to avoid running into "No space left on device" errors
      # when downloading multiple versions of IntelliJ for plugin verification
      - name: Maximize Build Space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true

      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Log Gradle cache size before Gradle tasks
        run: df -h

      - name: Log Gradle cache size before build
        run: du -sh ~/.gradle/caches || true

      - name: Execute buildHealth for build-logic
        run: './gradlew -p build-logic buildHealth -s'

      - name: Execute check
        run: './gradlew check -s'

      - name: Execute buildHealth for main project
        run: './gradlew buildHealth -s'

      - name: Log disk space after Gradle tasks
        if: always()
        run: df -h

      - name: Log Gradle cache size after build
        if: always()
        run: du -sh ~/.gradle/caches || true

      - name: Log final disk usage (top 20 largest directories)
        if: always()
        run: du -h | sort -hr | head -n 20

      - name: Clean up Gradle caches
        if: always()
        run: rm -rf ~/.gradle/caches

      - name: Log disk space after cleaning up Gradle caches
        if: always()
        run: df -h

      - name: Log Gradle cache size after cleaning up Gradle caches
        if: always()
        run: du -sh ~/.gradle/caches || true
