name: Test

on:
  pull_request:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual run'
        required: false

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gradle:
    runs-on:
      group: ubuntu-x86-runners
    steps:
      - name: Checkout the repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup java
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5

      - name: Execute buildHealth for build-logic
        run: './gradlew -p build-logic buildHealth -s'

      - name: Execute check
        run: './gradlew check -s'

      - name: Execute buildHealth for main project
        run: './gradlew buildHealth -s'

      # Gradle caches can exceed 45GB, potentially causing "No space left on device" errors.
      # Clean up caches to free disk space.
      - name: Clean up Gradle caches
        if: always()
        run: |
          echo "Disk space before cleanup:"
          df -h
          
          echo "Gradle cache size before cleanup:"
          du -sh ~/.gradle/caches || true
          
          echo "Cleaning up Gradle caches..."
          rm -rf ~/.gradle/caches
          
          echo "Disk space after cleanup:"
          df -h
