name: Main

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual run'
        required: false

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      # Free disk space to avoid running into "No space left on device" errors
      # when downloading multiple versions of IntelliJ for plugin verification
      - name: Maximize Build Space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
        with:
          tool-cache: true

      - name: Checkout the repo
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Setup java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4

      - name: Execute buildHealth for build-logic
        run: './gradlew -p build-logic buildHealth -s'

      - name: Execute check
        run: './gradlew check -s'

      - name: Execute buildHealth for main project
        run: './gradlew buildHealth -s'

      # Gradle caches can exceed 45GB, potentially causing "No space left on device" errors.
      # Clean up caches to free disk space.
      - name: Clean up Gradle caches
        if: always()
        run: |
          echo "Disk space before cleanup:"
          df -h
          
          echo "Gradle cache size before cleanup:"
          du -sh ~/.gradle/caches || true
          
          echo "Cleaning up Gradle caches..."
          rm -rf ~/.gradle/caches
          
          echo "Disk space after cleanup:"
          df -h
